<h1>Redis</h1>
<div class="tracy-inner">
	<div class="tracy-inner-container">
		<?php
		$i = 1;
		$c = count($connections);
		?>
		<?php foreach ($connections as $connection): ?>
			<table>
				<tr>
					<th>Connected:</th>
					<td>
						<?php if ($connection['client']->isConnected()) : ?>
							<strong>Yes</strong>
						<?php else: ?>
							<strong style="color: darkred;">No</strong>
							<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAABY0lEQVQ4T6XUPUgWUBTG8Z+ohO46iBKY6KDiJAQZlFgiIhiCSRAWBhEVBdEQTg4K1tDgqiiIOCgITeIi6NAQZDikoBCJEITQx9AQDXHgjr6veN87n+d/z+E8zylT/A1jLJWUoQbvMIm/p0mjqNCrw3t04jtu4Qf6sY+58wIrcYiLSfgIPxFdL2H1vMCoP0Ij/qEPTbiBN9jOAcbId/AFg6jGKJ7gIAe4jFl8TKD4IEZtxe8c4BS+YgHNqduetKhTl1lsyyF4gBa8wkts4TWuFLLGWcBreI7buItyDOFmLrAe62hL241uuzCSC4wJTlCLaRyjAS9ygaHbSWbuRXtKydtSgItYSTaJxYSN1koBPsP1FMFITBj7cynAKlzFhZTtvWIH6izbhLYCA7iEXWyUAgzfbabzFaB7mEFEMisp4blIySeM4zIe4n4usAPzCfIhHdluPM0Fhm4iRe0PfuExvhUC/gfifEIVhq4UvgAAAABJRU5ErkJggg=="/>
						<?php endif; ?>
					</td>
				</tr>
				<tr>
					<th>Name:</th>
					<td><?= $connection['name'] ?></td>
				</tr>
				<tr>
					<th>Ping:</th>
					<td><?= $connection['ping'] ?> (<?= number_format($connection['duration'], 4) ?> ms)</td>
				</tr>
				<?php if ($connection['dbSize'] !== FALSE): ?>
					<tr>
						<th>DB size:</th>
						<td><?= $connection['dbSize'] ?> keys</td>
					</tr>
				<?php endif; ?>
				<tr>
					<th><?php if (is_array($connection['uri'])): ?>Cluster:<?php else: ?>Server:<?php endif; ?></th>
					<td>
						<?php if (is_array($connection['uri'])):
							foreach ($connection['uri'] as $uri): ?><code><?= $uri ?></code><br><?php endforeach; ?>
						<?php else: ?>
							<code><?= $connection['uri'] ?></code>
						<?php endif; ?>
					</td>
				</tr>
				<tr>
					<th>Connection options:</th>
					<td><?php dump($connection['options']); ?></td>
				</tr>
			</table>
			<?php if ($c > $i): ?>
				<br>
			<?php endif; ?>
			<?php $i++; ?>
		<?php endforeach; ?>
		<?php if (count($commands)) : ?>
			<h2>Commands</h2>
			<table>
				<thead>
				<tr>
					<th>Connection</th>
					<th>Command</th>
					<th>Key</th>
					<th>Time</th>
					<th>Size</th>
				</tr>
				</thead>
				<tbody>
				<?php foreach ($commands as $command): ?>
					<tr>
						<td style="width:10%;"><?= $command[0] ?></td>
						<td style="width:10%;"><?= $command[1] ?></td>
						<td style="max-width:100px;overflow:hidden;text-overflow:ellipsis;"><?= $command[2] ?></td>
						<td style="width:10%;white-space:nowrap;"><?= $command[3] ?></td>
						<td style="width:10%;white-space:nowrap;"><?= $command[4] ?></td>
					</tr>
				<?php endforeach; ?>
				<?php if ($totalCommands > $maxCommands) : ?>
					<tr>
						<td colspan="4">... and <?php echo($totalCommands - $maxCommands); ?> more</td>
					</tr>
				<?php endif; ?>
				</tbody>
				<tfoot>
				<tr>
					<th>TOTAL:</th>
					<th colspan="2"><code><?= $totalCommands ?>x</code></th>
					<th style="width:10%;white-space:nowrap;"><code><?= $totalTime ?></code></th>
					<th style="white-space:nowrap;"><code><?= $totalSize ?></code></th>
				</tr>
				</tfoot>
			</table>
		<?php endif; ?>
	</div>
</div>
